### ISSUE TITLE
Propose Shifty API

### ISSUE THREAD

**Issue by tiagosimao** [irenical/thriftwizard#3]
Expose a proposal for the Shifty Java API

**Comment by tiagosimao** [comment]
### Approach proposal

A class (Shifty.class) that wraps and instruments the API implementation
A functional interface (java.util.function.Supplier) that retrieves a raw API implementation instance
For convenience, several Supplier factories may be provided.

A Shifty instance is configured with a single Supplier. Both Shifty and the Supplier may keep internal state and should be thread safe.

To take full advantage of eventual connection pooling, caching, and other mechanisms, the developer should to keep a reference to the Shifty object.

With this approach, calls to remote code **are not fully transparent**, as the object Shifty does not implement the API itself. An additional method call is needed.

### Usage proposal

#### Setup

In the examples bellow, this will be the our API implementation

``` java
public class MyUnstableApi {
  public String myRemoteMethod(Integer aNumber) {
    return aNumber.toString();
  }
}
```

Creating a supplier can be as simple as:

``` java
() -> new MyUnstableApi();
```

Therefore, the full setup could be:

``` java
Shifty<MyUnstableApi> shifty = new Shifty<MyUnstableApi>();
shifty.setSupplier(() -> new MyUnstableApi());
```

The developer should then keep a reference to the shifty instance. Shifty internals are thread safe and completely dynamic, so a shifty instance can be kept statically in the client application during the whole application life-cycle (one per remote API). There is no need of re-instantiate/reset the instance nor synchronise calls to it.

A supplier can also be a very complex thing. Service discovery, balancing and pooling capabilities should be address in the supplier implementation.

#### Usage

The method call() will return a proxied version of the API object (the one returned by the supplier). The code bellow is an example of a **synchronous** call.

``` java
String got = shifty.call().myRemoteMethod(9001);
Assert.assertEquals(got, "9001");
```

Two asynchronous calls are proposed. Callback-based and Future-based.

``` java
shifty.async((api) -> {
  got = api.myRemoteMethod(9001);
  Assert.assertEquals(got, "9001");
});
```

``` java
Future<String> future = shifty.async((api) -> {
  return api.myRemoteMethod(9001);
});
Assert.assertEquals(future.get(), "9001");
```

Shifty has a default ServiceExecutor implementation (Executors.newCachedThreadPool()?), but the developer can set some other.

``` java
shifty.setExecutorService(myLeetExecutorService);
```

**The existence of a ExecutorService is mandatory for async calls, the existence of the supplier is mandatory for all calls**

**Comment by claudiosf** [comment]
I like the approach. Very similar API to https://github.com/Netflix/Hystrix 
I didn't see any error handling mentioned on your proposal. Do you have any idea on how to deal with errors?

**Comment by tiagosimao** [comment]
Good point. I don't really know. I mean, the actual remote Exceptions will be thrown as normal, that's transparent. Network errors, timeout errors or some other interceptable stuff should be handled somehow. Maybe this could be a good approach: To have a pluggable fallback for when an underlying error occurs (probably then using hystrix's getFallback() method), if none is defined throwing a runtime exception might be a good enough simple approach.

``` java
shifty.call(()->"a fallback string").myRemoteMethod(9001);
```

This would also allow to throw a specific application exception

``` java
shifty.call(()->throw new MyException()).myRemoteMethod(9001);
```

I would also suggest to have another overload on call() and async() with an additional **long timeoutmillis** argument, since its a very common usecase.

``` java
shifty.call(3000).myRemoteMethod(9001);
```

A comprehensive example might come as

``` java
shifty.call(3000,()->"a fallback string").myRemoteMethod(9001);
```

A "global" timeout on instance level (shifty instance) might make sense also.
I'm not sure the fallback example above can have type safety.

**Comment by claudiosf** [comment]
The execution of a call starts to become quite verbose. Maybe we should consider something similar to what hystrix does. Wrapping the remote call in a Command class where all the call specific definitions can be defined.

**Comment by tiagosimao** [comment]
In that case I would prefer something like a builder instead. It seems to me that forcing the developer to use constructors makes it very very difficult to change later on. A constructor always means a "malloc", as in a non-constructor method it is up to the implementation. Also builders are hip!  
That's actually something I see as being ugly in the Hystrix API. Internally it actually has to keep static structures to avoid unnecessary instantiation and the like.

What about something like

``` java
shifty.call().withTimeout(3000).withFallback(()->"a fallback string").myRemoteMethod(9001);
```

or, a more direct translation from the constructor-based approach

``` java
Shifty<String> command = shifty.call().withTimeout(3000).withFallback(()->"a fallback string");

command.myRemoteMethod(9001);
```

**Comment by claudiosf** [comment]
I like the second approach. More elegant and makes reusing and passing the call around easier.

**Comment by tiagosimao** [comment]
OK cool. This will also keep the call() clean and increase readibility. I'll try to make a POC tomorrow.

**Comment by davidedpl** [comment]
I like the first proposed approach. Decoupling the target service api from the Shifty's one is probably better than making calls to remote service fully transparent and it adds the flexibility to choose for async calls.

I think the end user of this client should not be aware of the supplier's logic, but it should be provided a factory that, given the target class and some configuration, will return a Shifty client with the proper supplier. So the end user doesn't have do be fully aware of the protocol used to communicate with the target service. Anyway, if the idea is to keep Shifty more flexible the current approach is fine and a factory for Shifty clients could be provided by more specific frameworks (Thriftwizard?). The factory we're using in the Service Foundation project (http://git.io/vCJHG) could easily do this job.

Regarding the following discussion on how to configure the client, why do you want to specify configuration at every call instead of setting it up on client creation and providing some methods directly on the Shifty object do update it? (Actually I don't think updating client's configuration should be allowed, at least not so easily: if the client is shared inside the application it could be quite dangerous).

I had a look at Hystrix and in my understanding it's quite different from what we're trying to do: the command pattern they use allows to expose a single service method on each command object instead a complete service interface. I'm not saying I don't like it, it could be a good solution and maybe we could also use that instead developing something from scratch, but it's a different approach that will bring to having a client per endpoint instead one per service.

**Comment by tiagosimao** [comment]
As you say, there could be factory supplied shifty instances. Some helper libraries containing specific factories in shifty repository might also come in handy.  

The reason configuration is needed per-call is this: Different remote methods have different fallbacks and different timeouts. I do agree that you might want to set a more global timeout though, or even a global (exception throwing kind of thing) fallback. Pre-configuring these behaviours will force you to define each method call (command) separately (as in Hystrix). 
I guess we could go for both approaches. Fact is that in the fallback proposal above, we do have type safety concerns. One can ser a fallback that makes sense if he/she calls a(), but when the time comes b() is called instead, or even more that one method. Is there a way we can avoid this? Should we avoid more than one call per proxy?

**Comment by dneves** [comment]
after some thoughts:
- Shifty builder should be inverted, that is, shifty.withTimeout().withFallback().call() or shifty.withTimeout().withFallback().async() as shifty api should be the same for both cases.
- call() should lazy load the final api, as there should not be exceptions until a remote method is called (we may want to catch network exceptions but not remote user exceptions)
- as far as type safety for fallback and remote method calls, maybe if the shifty api for call() would be the same as async() would give us more control over what remote method could actually be called. Might be more verbose though

i do agree with a 'default' configuration (optional) with overrides per method call

also, it may be an option to let shifty constructor receive the supplier, if that would let us take some decisions earlier ... i don't think it's wrong to use the constructor, this lets us define a clear dependency on a supplier... after all, without a supplier, shifty wont do anything.

**Comment by davidedpl** [comment]
I understand that it may be needed a different configuration for different remote methods, my biggest concern is having this configuration set every time a method is called. I'd be much better (and safer) to set it once when creating the client and then just using it.

We could provide a way to define per-method configuration while creating the client instance instead of when making each call. Something like:

``` java
ShiftyBuilder<MyUnstableApi> clientBuilder =    
    Shifty.buildClient(MyUnstableApi.class).withGlobalConf(conf);
clientBuilder.withPerMethodConf("methodName").withFallback(()->"a fallback string");
Shifty<MyUnstableApi> apiClient = clientBuilder.build();
```

**Comment by tiagosimao** [comment]
Yes, a fallback mapping might do the trick. Using the method name (string) is the only thing that bothers me in that approach. Maybe MyUnstableApi::methodName might work? Not sure.  
I'll try to compile all of these suggestions in a JUnit test with a somewhat dummy implementation.

**Comment by davidedpl** [comment]
Yeah, the method name as string bothers me too since it can't be validated at compile time. I was also thinking about something like the way Mockito allows to define behaviours on methods (the `when(mock.someMethod("some arg")).thenReturn("foo")` stuff), but it's way too overcomplicated. 

If you could solve it with MyUnstableApi::methodName would be great, but it works only for methods without parameters, doesn't it?

**Comment by tiagosimao** [comment]
I don't even know if it's possible to use a lambda as a pointer to a method. If possible, overloads would break (but with the string approach the same happens).

**Comment by tiagosimao** [comment]
Initial implementation as discussed above.
https://github.com/irenical/shifty
